seed: 0
data_parameters:
  data_path: '/home/inspur/zhengchao/datasets'
  dataset: 'Receipt'
  valid_ratio: 0.2
  k_fold_num: 3

model_parameters:
  model_name: 'PTE'
  batch_size: 1024
  num_epochs: 10
  dimension: 128
  dropout: 0.15
  learning_rate: 0.0001
  max_patience_num: 50
  beta: 10