seed: 0
data_parameters:
  data_path: '/home/inspur/zhengchao/datasets'
  dataset: 'Receipt'
  # dataset: 'Sepsis'
  valid_ratio: 0.2

model_parameters:
  model_name: 'PTE'
  batch_size: 512
  num_epochs: 100
  dimension: 64
  dropout: 0.15
  learning_rate: 0.0001
  max_patience_num: 50
  beta: 10